debug

diff --git a/build/azDevOps/templates/setup.yml b/build/azDevOps/templates/setup.yml
--- a/build/azDevOps/templates/setup.yml
+++ b/build/azDevOps/templates/setup.yml
@@ -14,3 +14,11 @@ steps:
       script: |
         sudo wget https://github.com/Ensono/taskctl/releases/download/v${{ parameters.TaskctlVersion }}/taskctl_${{ parameters.TaskctlVersion }}_linux_amd64.tar.gz -O /tmp/taskctl.tar.gz
         sudo tar zxf /tmp/taskctl.tar.gz -C /usr/local/bin taskctl
+
+  - script: |
+      echo "Current directory: $(PWD)"
+      echo "Repo contents:"
+      ls -a
+      cat .git/config || echo ".git not found"
+    workingDirectory: $(PWD)
+    displayName: "Debug: Check Git visibility"
